name = "dcr-sicily-cars"
pages_build_output_dir = "./dist"
compatibility_date = "2026-07-21"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB"
database_name = "dcr-messages"
database_id = "<YOUR_DATABASE_ID>"
