CREATE TABLE IF NOT EXISTS vehicles (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  brand TEXT NOT NULL,
  model TEXT NOT NULL,
  year INTEGER NOT NULL,
  mileage INTEGER NOT NULL DEFAULT 0,
  price INTEGER NOT NULL DEFAULT 0,
  fuel TEXT NOT NULL DEFAULT '',
  transmission TEXT NOT NULL DEFAULT '',
  image TEXT NOT NULL DEFAULT '/assets/images/placeholder-car.svg',
  gallery TEXT NOT NULL DEFAULT '[]',
  badge TEXT DEFAULT NULL,
  featured INTEGER NOT NULL DEFAULT 0,
  description_it TEXT NOT NULL DEFAULT '',
  description_en TEXT NOT NULL DEFAULT '',
  color_ext TEXT NOT NULL DEFAULT '',
  color_int TEXT NOT NULL DEFAULT '',
  doors TEXT NOT NULL DEFAULT '',
  power_cv TEXT NOT NULL DEFAULT '',
  power_kw TEXT NOT NULL DEFAULT '',
  co2 TEXT NOT NULL DEFAULT '',
  euro_class TEXT NOT NULL DEFAULT '',
  consumption TEXT NOT NULL DEFAULT '',
  registration TEXT NOT NULL DEFAULT '',
  warranty INTEGER NOT NULL DEFAULT 0,
  created_at TEXT NOT NULL DEFAULT (datetime('now')),
  updated_at TEXT NOT NULL DEFAULT (datetime('now'))
);
